// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./../src/components/DarkModeToggle/src/DarkModeToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default']
    SwitchLanguage: typeof import('./../src/components/SwitchLanguage/src/SwitchLanguage.vue')['default']
    SwitchTheme: typeof import('./../src/components/SwitchTheme/src/SwitchTheme.vue')['default']
  }
}

export {}
