// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./../src/components/DarkModeToggle/src/DarkModeToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    SvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default']
    SwitchTheme: typeof import('./../src/components/SwitchTheme/src/SwitchTheme.vue')['default']
  }
}

export {}
